name: Create tag based on the release branch name

on:
  workflow_call:
    secrets:
      awsAccountID:
        required: true
      awsRegion:
        required: true
      slackBuildWebhook:
        required: true

jobs:
  release_tag:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout the files
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Validate release tag
        shell: bash
        run: |
          version=${{ steps.extract_branch.outputs.branch }};
          server_regex="^v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$";
          if [[ ! "$version" =~ $SEMVER_REGEX ]]; then echo "Version $version doesn't match semver"; fi