name: Validate helm chart

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
    secrets:
      slackBuildWebhook:
        required: true

jobs:
  validate_helm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the files
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install helm cli
        run: |
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          sudo apt-get install apt-transport-https --yes
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
      - name: Run linter towards helm chart
        run: |
          helm lint ${{ inputs.path }}

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slackBuildWebhook }}
